Bitso

In [108]:
import pandas as pd
# Ruta al archivo subido
file_path = "D:\\Users\\OneDrive\\Escritorio\\DA & BA\\Work\\Tisagar\\Bitso\\Bitso 1er semana julio.csv"

# Leer el archivo como texto y eliminar las comillas dobles
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# Reemplazar las comillas dobles
content = content.replace('"', '')

# Guardar el contenido limpio en un nuevo archivo temporal
temp_file_path = "D:\\Users\\OneDrive\\Escritorio\\DA & BA\\Work\\Tisagar\\Bitso\\Bitso 1er semana julio.csv"
with open(temp_file_path, 'w', encoding='utf-8') as file:
    file.write(content)

# Leer el archivo limpio con pandas
df = pd.read_csv(temp_file_path, delimiter=';')

In [109]:
columnas_delete = ['amount','fee']
df = df.drop(columns=columnas_delete)

In [110]:
# Intentar corregir los formatos si es necesario (ejemplo para formatos sin segundos)
df['datetime'] = df['datetime'].str.replace(r'(\d{1,2}/\d{1,2}/\d{4} \d{2}:\d{2})$', r'\1:00', regex=True)

In [111]:
# Intentar convertir la columna de fecha sin especificar el formato
df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')

In [112]:
# Extraer solo la fecha (sin la hora)
df['datetime'] = df['datetime'].dt.strftime('%m/%d/%Y')

In [113]:
df

    type major minor    rate        value        total   timestamp    datetime
0    buy  usdt   ars  1343,2  23926,02803  17,75570633  1721340989  07/18/2024
1    buy  usdt   ars  1338,5  35859,75785  26,70527204  1721339146  07/18/2024
2    buy  usdt   ars  1338,5  64951,42798  48,37025283  1721339145  07/18/2024
3    buy  usdt   ars  1338,1  28684,28128  21,42585691  1721338964  07/18/2024
4    buy  usdt   ars  1338,1  23908,37344  17,81022842  1721338953  07/18/2024
..   ...   ...   ...     ...          ...          ...         ...         ...
253  buy  usdt   ars  1412,7  49504,09249  34,93004841  1720388977  07/07/2024
254  buy  usdt   ars  1412,7   6378,57392    4,5007167  1720388973  07/07/2024
255  buy  usdt   ars  1412,7  30542,92905  21,55106653  1720388972  07/07/2024
256  buy  usdt   ars  1412,7  50903,03831  35,91714348  1720388969  07/07/2024
257  buy  usdt   ars  1412,7   143493,929  101,2492026  1720388963  07/07/2024

[258 rows x 8 columns]

In [114]:
df_compra = df[df['type'] == 'buy']
df_venta = df[df['type'] == 'sell']

In [115]:
df_c = df_compra.sort_values(by='datetime')
df_v = df_venta.sort_values(by='datetime')

In [116]:
df_c['Exchange compra'] = 'Bitso - Usdt'
df_c['Banco envio'] = 'Lemon'

df_v['Exchange Venta'] = 'Bitso - Usdt'
df_v['Banco recibo'] = 'Lemon'

In [117]:
columnas_ventas = ['datetime', 'Exchange Venta', 'value', 'rate', 'total', 'Banco recibo', 'timestamp','type']
columnas_compra = ['datetime','Exchange compra', 'value', 'rate', 'total', 'Banco envio', 'timestamp','type']

In [118]:
df_v = df_v[columnas_ventas]
df_c = df_c[columnas_compra]

In [119]:
df_v.to_excel('Bitso Ventas.xlsx', index=False)

In [120]:
df_c.to_excel('Bitso Compras.xlsx', index=False)

In [121]:
df_c.head(20)

,datetime,Exchange compra,value,rate,total,Banco envio,timestamp,type
257,07/07/2024,Bitso - Usdt,"143493,929","1412,7","101,2492026",Lemon,1720388963,buy
163,07/07/2024,Bitso - Usdt,"25663,90881","1421,55","17,99569787",Lemon,1720397215,buy
164,07/07/2024,Bitso - Usdt,"25601,69147","1421,55","17,95207066",Lemon,1720397213,buy
165,07/07/2024,Bitso - Usdt,"256007,647","1421,55","179,5142081",Lemon,1720397193,buy
166,07/07/2024,Bitso - Usdt,"20594,27916","1421,55","14,44084096",Lemon,1720397190,buy
167,07/07/2024,Bitso - Usdt,"7698,754579","1421,55","5,39841621",Lemon,1720397182,buy
168,07/07/2024,Bitso - Usdt,"14144,4225","1421,55","9,91816",Lemon,1720397137,buy
169,07/07/2024,Bitso - Usdt,"29475,54263","1421,55","20,66844001",Lemon,1720397124,buy
170,07/07/2024,Bitso - Usdt,"71052,5","1421,05","49,84",Lemon,1720397012,buy
171,07/07/2024,Bitso - Usdt,"517603,8046","1421,05","363,0748196",Lemon,1720397008,buy
172,07/07/2024,Bitso - Usdt,"255563,773","1418,7","179,5629583",Lemon,1720395948,buy
173,07/07/2024,Bitso - Usdt,"74903,016","1423,2","52,461584",Lemon,1720395926,buy
174,07/07/2024,Bitso - Usdt,"74903,016","1423,2","52,461584",Lemon,1720395925,buy
175,07/07/2024,Bitso - Usdt,"74903,016","1423,2","52,461584",Lemon,1720395925,buy
162,07/07/2024,Bitso - Usdt,"51584,4567","1421,55","36,17135271",Lemon,1720397218,buy
176,07/07/2024,Bitso - Usdt,"74903,016","1423,2","52,461584",Lemon,1720395924,buy
178,07/07/2024,Bitso - Usdt,"74903,016","1423,2","52,461584",Lemon,1720395923,buy
179,07/07/2024,Bitso - Usdt,"958235,358","1423,15","670,29006",Lemon,1720395923,buy
180,07/07/2024,Bitso - Usdt,"255802,8722","1416,2","180,0482298",Lemon,1720395791,buy
181,07/07/2024,Bitso - Usdt,"12784,1607","1417,05","8,99280293",Lemon,1720393971,buy